### ISSUE TITLE
enh: add `select` to `InterchangeFrame`

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#1263]
We should allow for selecting columns by name in `InterchangeFrame`, falling back to `select_columns_by_name` for generic dataframe interchange protocol implementers

**Comment by FBruzzesi** [comment]
Started to take a quick look at this. For DuckDB and Ibis it should be doable with native methods.

For `InterchangeFrame`, since we both store `_native_frame` and `_interchange_frame`, the latter can be slices with `select_columns_by_name`, yet, how do we return the former object?

From [a talk of yours](https://www.youtube.com/watch?v=gAGG21Ex1MQ&t=209s), is it by accessing `.dataframe` attribute? From the docs this is not very clear to me

**Comment by MarcoGorelli** [comment]
That was the "dataframe standard" 😄 The interchange protocol has no standardised way of getting the original dataframe object back 

I think we can implement this for duckdb and ibis for now

I've opened an issue about this in the dataframe-api repo, but I'm not holding my breath regarding a response/decision: https://github.com/data-apis/dataframe-api/issues/360
