### ISSUE TITLE
[Enh]: clarify and/or expand support for `int` column names for Pandas-like dataframes

### ISSUE THREAD

**Issue by EdAbati** [narwhals-dev/narwhals#571]
### We would like to learn about your use case. For example, if this feature is needed  to adopt Narwhals in an open source project, could you please enter the link to it below?

I was looking at how we support `int` column names while working on #355.

### Please describe the purpose of the new feature or describe the problem to solve.

ML libraries like `scikit-learn` currently support pandas dataframes created from numpy arrays with no column names. By default, pandas assigns an `int` index for each column in the array.

Certain methods already work with these int columns, others don't. For example, see:
```python
>>> import numpy as np
>>> import pandas as pd
>>> import narwhals as nw
>>> np_matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
>>> df = pd.DataFrame(np_matrix)
>>> nw_df = nw.from_native(df, eager_only=True)
```
- `nw_df get_columns(1)` works and also documents the use with `int` columns
- `nw.col(1)` works
- `nw.col(1).alias(4)` works
- `nw_df.rename({1 : 4})` works
- `nw_df.select(1)` or `DataFrame.select([0,1])` don't work: `AssertionError: Expected IntoExpr, got <class 'int'>` ❌
- `DataFrame.with_columns` works with `Expr` and doesn't work with `Series` ⚠️
```python
>>> nw.to_native(nw_df.with_columns(nw.col(1).alias(4)))
	0	1	2	4
0	1	2	3	2
1	4	5	6	5
2	7	8	9	8

>>> nw.to_native(nw_df.with_columns(nw_df.get_column(1).alias(4)))
TypeError: keywords must be strings
```

### Suggest a solution if possible.

We should decide whether we should fix the methods that don't work and also add a documentation page to clarify how to deal with `int` columns (and add the tests if they are missing to ensure we don't drop support for int columns).

My thoughts:
- `select` : allowing `DataFrame.select(<int>)` may be a bit weird. But I think we should suggest an alternative for example `DataFrame.select(nw.col(<int>))`
- `with_columns`:`nw_df.with_columns(nw_df.get_column(1).alias(4))` should be allowed. One may want to do some manipulation to a series before adding it to the dataframe

### Additional information that may help us understand your needs.

Please let me know if I missed something. There may be some decision or feature I missed 👀

What do you think @MarcoGorelli and @FBruzzesi ?

**Comment by FBruzzesi** [comment]
Thanks for reporting this! It is a very clear explanation of what is going on. I have a few questions/consideration.

## Being a Polars subset

I personally would opt to keep up the promise of being a strict subset of polars. I am personally not in favor of keeping the `int` col names (I would cast those to `str`) for pandas in the first place.

I understand it is a little special case, but it sets a case in which narwhals is/would be different.

## Downstream libraries

> ML libraries like scikit-learn currently support pandas dataframes created from numpy arrays with no column names

Let's use scikit-learn as an example: scikit-learn supports both pandas and polars, but these two libraries create different column names when passing an array without specifying columns/schema. Therefore in order to end up with the same results either:

1. this is addressed before creating the dataframe from the array, and there is one path forward 
2. there are two separate logic/workflows until "reconciliation"

Now we would _ask_ to act in the first scenario, i.e. deal with difference before, and then have a unified workflow based on polars API. As a library developer, to me this does not seems too bad, or at least less work/maintenance than handling different cases forward.

## Moving forward

> We should decide whether we should fix the methods

I expressed how I would like Narwhals to behave in the very first point 😇 I hope it didn't sound too harsh, it really wasn't the intention - the "Being a Polars subset" gives me a lot of clarity and know what to refer to when in doubt. 

> add a documentation page to clarify how to deal with int columns

Yes, more documentation, especially on edge cases is always welcomed.

**Comment by MarcoGorelli** [comment]
I think unfortunately non-string columns are a fact-of-life when dealing with pandas, and that we should opt to preserve the user's input as much as possible. Something we're aiming for is "support newer dataframe libraries at no cost to existing pandas users"

> But I think we should suggest an alternative for example DataFrame.select(nw.col(<int>))

Yup, agree. Non-string columns names should only be allowed in places where the argument unambiguously refers to a column by name - and so definitely not in `IntoExpr`. Otherwise, `nw.col('a') + 2` would be ambiguous

> nw.to_native(nw_df.with_columns(nw_df.get_column(1).alias(4)))

this should work, let's check

**Comment by MarcoGorelli** [comment]
> this should work, let's check

ah, it's cause `assign` already only supports string names in pandas itself

**Comment by MarcoGorelli** [comment]
> As a library developer, to me this does not seems too bad

I just checked, and disallowing non-string names would cause some test failures in scikit-lego - would you be ok with that?

**Comment by FBruzzesi** [comment]
> I just checked, and disallowing non-string names would cause some test failures in scikit-lego - would you be ok with that?

Let me guess, is it where we create a pandas dataframe from an array?!

```py
X = nw.from_native(X, strict=False, eager_only=True)
if not isinstance(X, nw.DataFrame):
    X = nw.from_native(pd.DataFrame(X))
```
?

The fix has two folds though:

- in narwhals we cast to string
- developers take that as an assumption (in our case we would convert `groups = [str(g) for f in groups]`)


Edit: I also realized that pandas can have `None` as a col name, and that would break the recently merged `PandasExprNameNamespace`, e.g. in this line `output_names = [prefix + str(name) for name in root_names]` as well as similar once - and the `str(name)` is there in the first place to handle numeric col names 


I don't know, shall we sleep on this for a bit longer?!

**Comment by EdAbati** [comment]
In general, I tend to agree with

> non-string columns are a fact-of-life when dealing with pandas, and that we should opt to preserve the user's input as much as possible. 

and complement this with a page in the docs that explains workarounds for edge cases. For example, it should be clear what to do with using `select` with int cols or with a `None` (I didn't know that it was possible!) col name.

Regarding, "in narwhals we cast to string" by default:

TBH I don't have a strong case against this, because I cannot think of a use case where I'd want to keep col names as integers. I can imagine that it could be mostly a consequence of the `pandas` default in the conversion from a numpy array. ( I may be very wrong)

Nevertheless, if we go for this, I think we should be careful to do that silently. Some ideas:
- We could just raise a warning explaining that the input columns are changed. ( A fun edge case could be `pd.DataFrame({1: [1,2], "1": [4,5])` 😅 )
- We could even consider to be more strict: only accept str columns in the first place and raise an Exception.
- We could add a new params to `nw.from_native(..., strict_column_names=True)` to allow the devs decide whether only string col names are allowed or not. In this case, we should be clear that we promise full support for dataframes with string column names only.

**Comment by MarcoGorelli** [comment]
@EdAbati I've taken a look at the scikit-learn diff you posted - I think it doesn't look too good for us if we need to raise a warning

It's an easy fix to allow for the snippet you posted https://github.com/narwhals-dev/narwhals/pull/595, let's just go with that?

**Comment by EdAbati** [comment]
Sounds good to me! Do you think we should also add a documentation/guide on how to deal with `int` cols? or maybe not yet?

**Comment by MarcoGorelli** [comment]
it would probably be a good idea, yes!
