### ISSUE TITLE
test: remove `to_list()` and `to_numpy()` from Series tests

### ISSUE THREAD

**Issue by MarcoGorelli** [narwhals-dev/narwhals#804]
Let's try to write all tests using `compare_dict` from `tests.utils`

The reason is that `to_list` forces all data into a list of Python objects, which isn't ideal:
- by then, we've lost all type information (we may well expand `compare_dicts` later to be stricter about that)
- cudf.Series doesn't implement `to_list`

If we just use `compare_dicts` across tests, then having a single source of determining whether `result` matches `expected` should help us out in the long-run

So, the task here is, when a test uses `to_list`, to rewrite it so that we're comparing dictionaries. See https://github.com/narwhals-dev/narwhals/pull/801 for several examples of how to do this

A couple of examples of functions that still need changing:
- tests/expr_and_series/dt/to_string_test.py
- test_ser_is_in

There's a few more

contributions welcome! if you're new, please read the CONTRIBUTING.md file, and choose one file at a time. no need to ask for permission to work on this

**Comment by specialkapa** [comment]
Hi @MarcoGorelli. Good to e-meet you. I have done some work to replace `to_list` and use `compare_dicts` instead. Tests seem to be passing. Followed the instruction on [CONTRIBUTING.md](https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md) but I cannot seem to push my local branch to the remote repository. Note that there is no remote branch that I am tracking. Rather I am trying to push using the command below: 

`git push --set-upstream origin test/804/remove-to-list-and-to-numpy`.

Am I missing something obvious? Should I create the remote branch and track it with the local one and then push? 

Thanks

**Comment by MarcoGorelli** [comment]
> `git push --set-upstream origin test/804/remove-to-list-and-to-numpy.`

yup, this looks fine 👍

**Comment by specialkapa** [comment]
Thanks for getting back to me. Upon executing the push command above I am prompted to type my user name and access token.  

But I get this error: 

remote: Permission to narwhals-dev/narwhals.git denied to specialkapa.
fatal: unable to access 'https://github.com/narwhals-dev/narwhals.git/': The requested URL returned error: 403

Apologies in case it is something obvious. I am used to using SSH rather than credentials. Any idea what that issue is?

**Comment by MarcoGorelli** [comment]
hey, I'd suggest working through https://github.com/firstcontributions/first-contributions before you try contributing

**Comment by specialkapa** [comment]
roger! thanks you :)

**Comment by luke396** [comment]
I'm also working on some code, but I'll push or merge it after @specialkapa fixes his environment. Welcome to our new contributor!

**Comment by MarcoGorelli** [comment]
thanks @luke396 ! it's unlikely that you worked on exactly the same files, and there'll be other issues for @specialkapa to work on, I'd suggest just pushing your code for now

**Comment by specialkapa** [comment]
hi @MarcoGorelli, silly me used the https clone URL rather than the SSH one. I am confident I am satisfying all instructions in https://github.com/firstcontributions/first-contributions but I seem to not have write access. Here is the feedback I get on my terminal:

_ERROR: Permission to narwhals-dev/narwhals.git denied to specialkapa.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists._

**Comment by specialkapa** [comment]
Ah thanks for this. I don't think I came across this requirements in the [CONTRIBUTING.md](https://github.com/narwhals-dev/narwhals/blob/main/CONTRIBUTING.md). Is this something that I missed or this something that is implied and I should have known?

**Comment by FBruzzesi** [comment]
Thanks for the feedback! You are right that none of what I have mentioned is explicitly stated in the guidelines we currently have. We will add some of these necessary preliminary steps for more clarity👌

**Comment by MarcoGorelli** [comment]
I think it's also mentioned there: https://github.com/firstcontributions/first-contributions?tab=readme-ov-file#fork-this-repository

**Comment by specialkapa** [comment]
@MarcoGorelli you're right. Thanks for pointing this out.
